steps:
  - id: build-component-docker-images
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |

        ls /
        ls -a /workspace
        cd components



        echo "2. Building & Push Docker Component TFDV"
        cd tfdv
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:$COMMIT_SHA -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:$COMMIT_SHA
        cd ..



options:
  machineType: 'N1_HIGHCPU_8'

timeout: 2400s
