steps:
  - id: build-component-docker-images
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |

        ls /
        ls -a /workspace
        cd components

        echo "Building Pipeline Components Docker Images..."
        echo "---------------------------------------------"

        echo "1. Building Docker Component Base Image"
        cd base
        mkdir - ./build
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:$COMMIT_SHA -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:$COMMIT_SHA
        rm -rf ./build
        cd ..

        echo "2. Building Docker Component TFDV"
        cd tfdv
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:$COMMIT_SHA -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:$COMMIT_SHA
        cd ..