steps:
  - id: build-component-docker-images
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |

        ls /
        ls -a /workspace
        cd components

        echo "Building Pipeline Components Docker Images..."
        echo "---------------------------------------------"

        echo "1. Building & Push Docker Component Base Image"
        cd base
        mkdir - ./build
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:$COMMIT_SHA -f Dockerfile .
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:latest -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:$COMMIT_SHA
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:latest
        rm -rf ./build
        cd ..

        echo "2. Building & Push Docker Component TFDV"
        cd tfdv
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:$COMMIT_SHA -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:$COMMIT_SHA
        cd ..

        echo "3. Build & Push Docker Component TFMA"
        cd tfma
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfma:$COMMIT_SHA -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfma:$COMMIT_SHA
        cd ..

        echo "4. Build & Push Docker Component TFT"
        cd tft
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tft:$COMMIT_SHA -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tft:$COMMIT_SHA
        cd ..

        echo "5. Build & Push Docker Component Predict"
        cd predict
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tf-predict:$COMMIT_SHA -f Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tf-predict:$COMMIT_SHA
        cd ..