steps:
  - id: build-component-docker-images
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |

        ls /
        ls -a /workspace
        cd components

        echo "Building Pipeline Components Docker Images..."
        echo "---------------------------------------------"
        echo "1. Building Docker Component Base Image"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:$COMMIT_SHA -f base/Dockerfile .