steps:
  - id: build-component-docker-images
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        echo "Building Pipeline Components Docker Images..."
        echo "---------------------------------------------"
        echo "1. Building Docker Component Base Image"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:$COMMIT_SHA -f base/Dockerfile .

        echo "2. Building Docker Component TFDV"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:$COMMIT_SHA -f tfdv/Dockerfile .

        echo "3. Building Docker Component TFMA"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfma:$COMMIT_SHA -f tfma/Dockerfile .

        echo "4. Building Docker Component TFT"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tft:$COMMIT_SHA -f tft/Dockerfile .

        echo "5. Building Docker Component Predict"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tf-predict:$COMMIT_SHA -f predict/Dockerfile .