steps:
  - id: build-component-docker-images
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        echo "Build & Push Pipeline Components Docker Images..."
        echo "---------------------------------------------"
        echo "1. Building & Push Docker Component Base Image"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:dev -f base/Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-base:dev

        echo "2. Building Docker Component TFDV"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:dev -f tfdv/Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfdv:dev

        echo "3. Building Docker Component TFMA"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfma:dev -f tfma/Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tfma:dev

        echo "4. Building Docker Component TFT"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tft:dev -f tft/Dockerfile .
        docker push gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tft:dev

        echo "5. Building Docker Component Predict"
        docker build -t gcr.io/$PROJECT_ID/ml-pipeline-dataflow-tf-predict:dev -f predict/Dockerfile .
        docker push ml-pipeline-dataflow-tf-predict:dev

